# Generated by Django 4.2.4 on 2023-08-05 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('sobrenome', models.CharField(blank=True, max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('data_nascimento', models.DateField(max_length=8)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.CharField(blank=True, max_length=20)),
                ('sexo', models.CharField(max_length=1)),
                ('cep', models.IntegerField(default=0)),
                ('inativo', models.BooleanField(default=False)),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
