# Generated by Django 4.2.4 on 2023-08-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_imovel_foto_alter_imovel_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='foto',
            field=models.ImageField(default='default.png', upload_to='imoveis/', verbose_name='Foto do Imóvel'),
        ),
    ]
