# Generated by Django 4.2.4 on 2023-08-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_imovel_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovel',
            options={'verbose_name': 'Imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
        migrations.AlterField(
            model_name='imovel',
            name='foto',
            field=models.ImageField(default='imoveis/default.png', upload_to='imoveis/', verbose_name='Foto do Imóvel'),
        ),
    ]
