# Generated by Django 4.2.4 on 2023-08-19 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_imovel_options_alter_imovel_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='foto',
        ),
        migrations.CreateModel(
            name='FotosDosImoveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='imoveis/default.png', upload_to='imoveis/', verbose_name='Foto do Imóvel')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.imovel')),
            ],
        ),
    ]
