# Generated by Django 4.2.4 on 2023-08-19 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_fotosdosimoveis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='data_geracao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
