# Generated by Django 4.2.4 on 2023-08-19 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_imovel_data_geracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='data_geracao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
