# Generated by Django 4.2.4 on 2023-08-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_imovel_destaque_alter_imovel_data_geracao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoimovel',
            options={'verbose_name': 'Tipo de Imóvel', 'verbose_name_plural': 'Tipos de Imóveis'},
        ),
    ]
