# Generated by Django 4.2.4 on 2023-08-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_tipoimovel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
