# Generated by Django 4.2.4 on 2023-08-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_imovel_visualizacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço do Imóvel'),
        ),
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
