# Generated by Django 4.2.4 on 2023-08-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_imovel_preco_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedesSociais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=300, verbose_name='Facebook')),
                ('instagram', models.CharField(max_length=300, verbose_name='Instagram')),
                ('whatsapp', models.CharField(max_length=300, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Socias',
            },
        ),
        migrations.AlterModelOptions(
            name='imovel',
            options={'ordering': ['titulo'], 'verbose_name': 'Imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
        migrations.AlterModelOptions(
            name='tipoimovel',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de Imóvel', 'verbose_name_plural': 'Tipos de Imóveis'},
        ),
    ]
