# Generated by Django 4.2.4 on 2023-08-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_redessociais_alter_imovel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textosdofooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quem_somos', models.TextField(help_text="Insira o texto para ser exibido ao clicar em 'Quem Somos.'", verbose_name="Texto 'Quem Somos'")),
                ('fale_conosco', models.TextField(help_text="Insira o texto para ser exibido ao clicar em 'Fale Conosco.'", verbose_name="Texto 'Fale Conosco'")),
                ('termos_condicoes', models.TextField(help_text="Insira o texto para ser exibido ao clicar em 'termos e Condições.'", verbose_name="Texto 'Termos e Condições'")),
            ],
            options={
                'verbose_name': 'Texto do roda-pé',
                'verbose_name_plural': 'Textos do roda-pé',
            },
        ),
        migrations.AlterField(
            model_name='redessociais',
            name='facebook',
            field=models.CharField(help_text='Insira o link para a página do Facebook.', max_length=300, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='redessociais',
            name='instagram',
            field=models.CharField(help_text='Insira o link para a página do Instagram.', max_length=300, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='redessociais',
            name='whatsapp',
            field=models.CharField(help_text='Insira o link para a contado do Whatsapp.', max_length=300, verbose_name='WhatsApp'),
        ),
    ]
