# Generated by Django 4.2.4 on 2023-08-31 22:06

import Carbono.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedesSociais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(help_text='Insira o link para a página do Facebook.', max_length=300, verbose_name='Facebook')),
                ('instagram', models.CharField(help_text='Insira o link para a página do Instagram.', max_length=300, verbose_name='Instagram')),
                ('whatsapp', models.CharField(help_text='Insira o link para a contado do Whatsapp.', max_length=300, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Socias',
            },
        ),
        migrations.CreateModel(
            name='Textosdofooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quem_somos', models.TextField(help_text="Insira o texto para ser exibido ao clicar em 'Quem Somos.'", verbose_name="Texto 'Quem Somos'")),
                ('fale_conosco', models.TextField(help_text="Insira o texto para ser exibido ao clicar em 'Fale Conosco.'", verbose_name="Texto 'Fale Conosco'")),
                ('termos_condicoes', models.TextField(help_text="Insira o texto para ser exibido ao clicar em 'termos e Condições.'", verbose_name="Texto 'Termos e Condições'")),
            ],
            options={
                'verbose_name': 'Texto do roda-pé',
                'verbose_name_plural': 'Textos do roda-pé',
            },
        ),
        migrations.CreateModel(
            name='TipoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Imóvel',
                'verbose_name_plural': 'Tipos de Imóveis',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Imóvel')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço do Imóvel')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('qtd_quartos', models.IntegerField(verbose_name='Qtd Quartos')),
                ('qtd_banheiros', models.IntegerField(verbose_name='Qtd Banheiros')),
                ('qtd_comodos', models.IntegerField(verbose_name='Qtd Comodos Totais')),
                ('data_geracao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('destaque', models.BooleanField(default=False)),
                ('visualizacoes', models.PositiveIntegerField(default=0, editable=False)),
                ('tipo_imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carbono.tipoimovel', verbose_name='Tipo do Imóvel')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='FotosDosImoveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=Carbono.models.upload_to)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carbono.imovel')),
            ],
            options={
                'verbose_name': 'Foto do Imóvel',
                'verbose_name_plural': 'Fotos dos Imóveis',
            },
        ),
    ]
